language: go
os:
  - linux

go:
- "1.9.x"
- "1.10.x"
- master

go_import_path: tapr.space

install: true

matrix:
  allow_failures:
    - go: master

  fast_finish: true

notifications:
  email: false

script:
  - find . -path ./vendor -prune -o -name '*.go' -type f | xargs gofmt -s -l
  - go test -short -race ./...

