// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tapr.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	tapr.proto

It has these top-level messages:
	StatRequest
	StatResponse
	PushPrepareRequest
	PushPrepareResponse
	PushRequest
	PushResponse
	PushLogRequest
	PushLogEntry
	PullPrepareRequest
	PullPrepareResponse
	PullRequest
	Chunk
	Vector
	LogTailRequest
	LogEvent
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type LogLevel int32

const (
	LogLevel_Debug    LogLevel = 0
	LogLevel_Info     LogLevel = 1
	LogLevel_Warning  LogLevel = 2
	LogLevel_Error    LogLevel = 3
	LogLevel_Disabled LogLevel = 4
)

var LogLevel_name = map[int32]string{
	0: "Debug",
	1: "Info",
	2: "Warning",
	3: "Error",
	4: "Disabled",
}
var LogLevel_value = map[string]int32{
	"Debug":    0,
	"Info":     1,
	"Warning":  2,
	"Error":    3,
	"Disabled": 4,
}

func (x LogLevel) String() string {
	return proto1.EnumName(LogLevel_name, int32(x))
}
func (LogLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *StatRequest) Reset()                    { *m = StatRequest{} }
func (m *StatRequest) String() string            { return proto1.CompactTextString(m) }
func (*StatRequest) ProtoMessage()               {}
func (*StatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StatRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StatResponse struct {
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
}

func (m *StatResponse) Reset()                    { *m = StatResponse{} }
func (m *StatResponse) String() string            { return proto1.CompactTextString(m) }
func (*StatResponse) ProtoMessage()               {}
func (*StatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type PushPrepareRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Append bool   `protobuf:"varint,3,opt,name=append" json:"append,omitempty"`
}

func (m *PushPrepareRequest) Reset()                    { *m = PushPrepareRequest{} }
func (m *PushPrepareRequest) String() string            { return proto1.CompactTextString(m) }
func (*PushPrepareRequest) ProtoMessage()               {}
func (*PushPrepareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PushPrepareRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PushPrepareRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PushPrepareRequest) GetAppend() bool {
	if m != nil {
		return m.Append
	}
	return false
}

type PushPrepareResponse struct {
	Tx    []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *PushPrepareResponse) Reset()                    { *m = PushPrepareResponse{} }
func (m *PushPrepareResponse) String() string            { return proto1.CompactTextString(m) }
func (*PushPrepareResponse) ProtoMessage()               {}
func (*PushPrepareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PushPrepareResponse) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *PushPrepareResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

// PushRequest is sent as the first message to the push endpoint, followed
// by a stream of Chunk messages.
type PushRequest struct {
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto1.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PushRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type PushResponse struct {
	Error []byte `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *PushResponse) Reset()                    { *m = PushResponse{} }
func (m *PushResponse) String() string            { return proto1.CompactTextString(m) }
func (*PushResponse) ProtoMessage()               {}
func (*PushResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PushResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type PushLogRequest struct {
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (m *PushLogRequest) Reset()                    { *m = PushLogRequest{} }
func (m *PushLogRequest) String() string            { return proto1.CompactTextString(m) }
func (*PushLogRequest) ProtoMessage()               {}
func (*PushLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PushLogRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type PushLogEntry struct {
	Seq   int64  `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *PushLogEntry) Reset()                    { *m = PushLogEntry{} }
func (m *PushLogEntry) String() string            { return proto1.CompactTextString(m) }
func (*PushLogEntry) ProtoMessage()               {}
func (*PushLogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PushLogEntry) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PushLogEntry) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type PullPrepareRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *PullPrepareRequest) Reset()                    { *m = PullPrepareRequest{} }
func (m *PullPrepareRequest) String() string            { return proto1.CompactTextString(m) }
func (*PullPrepareRequest) ProtoMessage()               {}
func (*PullPrepareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PullPrepareRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PullPrepareRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PullPrepareResponse struct {
	Tx    []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Error []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *PullPrepareResponse) Reset()                    { *m = PullPrepareResponse{} }
func (m *PullPrepareResponse) String() string            { return proto1.CompactTextString(m) }
func (*PullPrepareResponse) ProtoMessage()               {}
func (*PullPrepareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PullPrepareResponse) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *PullPrepareResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type PullRequest struct {
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (m *PullRequest) Reset()                    { *m = PullRequest{} }
func (m *PullRequest) String() string            { return proto1.CompactTextString(m) }
func (*PullRequest) ProtoMessage()               {}
func (*PullRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PullRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type Chunk struct {
	// stream transaction
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// contained data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// error (used only in pull)
	Error []byte `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto1.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Chunk) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *Chunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Chunk) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type Vector struct {
	Split  bool     `protobuf:"varint,1,opt,name=split" json:"split,omitempty"`
	Names  []string `protobuf:"bytes,2,rep,name=names" json:"names,omitempty"`
	Values [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto1.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Vector) GetSplit() bool {
	if m != nil {
		return m.Split
	}
	return false
}

func (m *Vector) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Vector) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type LogTailRequest struct {
	Level LogLevel `protobuf:"varint,1,opt,name=level,enum=proto.LogLevel" json:"level,omitempty"`
}

func (m *LogTailRequest) Reset()                    { *m = LogTailRequest{} }
func (m *LogTailRequest) String() string            { return proto1.CompactTextString(m) }
func (*LogTailRequest) ProtoMessage()               {}
func (*LogTailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LogTailRequest) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_Debug
}

type LogEvent struct {
	Level   LogLevel `protobuf:"varint,1,opt,name=level,enum=proto.LogLevel" json:"level,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *LogEvent) Reset()                    { *m = LogEvent{} }
func (m *LogEvent) String() string            { return proto1.CompactTextString(m) }
func (*LogEvent) ProtoMessage()               {}
func (*LogEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *LogEvent) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_Debug
}

func (m *LogEvent) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*StatRequest)(nil), "proto.StatRequest")
	proto1.RegisterType((*StatResponse)(nil), "proto.StatResponse")
	proto1.RegisterType((*PushPrepareRequest)(nil), "proto.PushPrepareRequest")
	proto1.RegisterType((*PushPrepareResponse)(nil), "proto.PushPrepareResponse")
	proto1.RegisterType((*PushRequest)(nil), "proto.PushRequest")
	proto1.RegisterType((*PushResponse)(nil), "proto.PushResponse")
	proto1.RegisterType((*PushLogRequest)(nil), "proto.PushLogRequest")
	proto1.RegisterType((*PushLogEntry)(nil), "proto.PushLogEntry")
	proto1.RegisterType((*PullPrepareRequest)(nil), "proto.PullPrepareRequest")
	proto1.RegisterType((*PullPrepareResponse)(nil), "proto.PullPrepareResponse")
	proto1.RegisterType((*PullRequest)(nil), "proto.PullRequest")
	proto1.RegisterType((*Chunk)(nil), "proto.Chunk")
	proto1.RegisterType((*Vector)(nil), "proto.Vector")
	proto1.RegisterType((*LogTailRequest)(nil), "proto.LogTailRequest")
	proto1.RegisterType((*LogEvent)(nil), "proto.LogEvent")
	proto1.RegisterEnum("proto.LogLevel", LogLevel_name, LogLevel_value)
}

func init() { proto1.RegisterFile("tapr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0x49, 0xdc, 0x74, 0xd3, 0x69, 0x54, 0x22, 0x83, 0x50, 0x2e, 0x48, 0xc1, 0x02, 0xa9,
	0xe2, 0xb0, 0x07, 0x90, 0xe0, 0xc0, 0x05, 0xc4, 0xf6, 0x80, 0xc8, 0x61, 0x65, 0x10, 0x70, 0x75,
	0xe9, 0x34, 0x1b, 0xe1, 0xb5, 0xb3, 0xb6, 0x53, 0x2d, 0xfc, 0x7a, 0x64, 0x3b, 0x5b, 0x0a, 0xa8,
	0x08, 0x38, 0x75, 0x9e, 0xfd, 0xe6, 0xf3, 0xcc, 0x6b, 0x00, 0x9c, 0xe8, 0xcd, 0x69, 0x6f, 0xb4,
	0xd3, 0x34, 0x0b, 0x3f, 0xec, 0x01, 0xcc, 0xdf, 0x39, 0xe1, 0x38, 0x5e, 0x0d, 0x68, 0x1d, 0xa5,
	0x30, 0x51, 0xe2, 0x12, 0xab, 0xa4, 0x4e, 0x96, 0x33, 0x1e, 0x6a, 0xc6, 0xa0, 0x88, 0x16, 0xdb,
	0x6b, 0x65, 0xd1, 0x7b, 0x6c, 0xf7, 0x2d, 0x7a, 0x08, 0x0f, 0x35, 0xfb, 0x04, 0xf4, 0x7c, 0xb0,
	0x17, 0xe7, 0x06, 0x7b, 0x61, 0xf0, 0x0f, 0x34, 0x7a, 0x0f, 0xa6, 0x7a, 0xbb, 0xb5, 0xe8, 0xaa,
	0x34, 0xf4, 0x8f, 0xca, 0x9f, 0x8b, 0xbe, 0x47, 0xb5, 0xa9, 0x48, 0x9d, 0x2c, 0x73, 0x3e, 0x2a,
	0xf6, 0x02, 0xee, 0xfc, 0x44, 0x1e, 0x87, 0x58, 0x40, 0xea, 0xae, 0x03, 0xb8, 0xe0, 0xa9, 0xbb,
	0xa6, 0x77, 0x21, 0x43, 0x63, 0xb4, 0x09, 0xd4, 0x82, 0x47, 0xc1, 0xee, 0xc3, 0xdc, 0x37, 0xdf,
	0xcc, 0xf3, 0x4b, 0x13, 0x7b, 0x08, 0x45, 0xbc, 0x1e, 0xa1, 0x7b, 0x48, 0x72, 0x08, 0xa9, 0x61,
	0xe1, 0x5d, 0x8d, 0x6e, 0x8f, 0x71, 0x9e, 0x45, 0x4e, 0xa3, 0xdb, 0x95, 0x72, 0xe6, 0x2b, 0x2d,
	0x81, 0x58, 0xbc, 0x1a, 0x03, 0xf2, 0xe5, 0x91, 0xf1, 0x5e, 0xfa, 0xd4, 0xa4, 0xfc, 0xff, 0xd4,
	0x62, 0x3a, 0x07, 0x84, 0x7f, 0x4f, 0x47, 0xca, 0x63, 0x5b, 0xbd, 0x82, 0xec, 0xf5, 0xc5, 0xa0,
	0xbe, 0xfc, 0x46, 0xa3, 0x30, 0xd9, 0x08, 0x27, 0x46, 0x58, 0xa8, 0x7f, 0xbc, 0x40, 0x0e, 0x5f,
	0x68, 0x60, 0xfa, 0x01, 0x3f, 0x3b, 0x6d, 0xfc, 0xbd, 0xed, 0x65, 0xe7, 0x02, 0x26, 0xe7, 0x51,
	0xf8, 0x53, 0xbf, 0x9e, 0xad, 0xd2, 0x9a, 0x2c, 0x67, 0x3c, 0x0a, 0xbf, 0xec, 0x4e, 0xc8, 0x01,
	0x6d, 0x45, 0x6a, 0xb2, 0x2c, 0xf8, 0xa8, 0xd8, 0x73, 0x58, 0x34, 0xba, 0x7d, 0x2f, 0xba, 0xfd,
	0xc8, 0x8f, 0x20, 0x93, 0xb8, 0x43, 0x19, 0xa8, 0x8b, 0x27, 0xb7, 0xe3, 0xb7, 0x7d, 0xda, 0xe8,
	0xb6, 0xf1, 0xc7, 0x3c, 0xde, 0xb2, 0xb7, 0x90, 0xfb, 0xff, 0x66, 0x87, 0xea, 0x6f, 0x5b, 0x68,
	0x05, 0x27, 0x97, 0x68, 0xad, 0x68, 0x31, 0xac, 0x39, 0xe3, 0x37, 0xf2, 0xf1, 0x2a, 0xc0, 0x82,
	0x99, 0xce, 0x20, 0x3b, 0xc3, 0xf5, 0xd0, 0x96, 0xb7, 0x68, 0x0e, 0x93, 0x37, 0x6a, 0xab, 0xcb,
	0x84, 0xce, 0xe1, 0xe4, 0xa3, 0x30, 0xaa, 0x53, 0x6d, 0x99, 0x7a, 0xc7, 0xca, 0x47, 0x51, 0x12,
	0x5a, 0x40, 0x7e, 0xd6, 0x59, 0xb1, 0x96, 0xb8, 0x29, 0x27, 0xeb, 0x69, 0x78, 0xf7, 0xe9, 0xf7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xca, 0x43, 0x8f, 0x94, 0x03, 0x00, 0x00,
}
